name: Run Super Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Adjust according to your PHP version requirement

      - name: Install Composer dependencies
        run: |
          # Navigate to the baranitech-be directory
          cd baranitech-be
          
          # Install Composer
          curl -sS https://getcomposer.org/installer | php
          
          # Run composer install in the correct directory
          php composer.phar install --no-interaction --prefer-dist

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: false
