name: Suber-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: actions/super-linter@v3
    env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}